Fix missing service_id param
Bandaid fix to get pull_alerts.py working again; somehow https://github.com/lyft/opsreview/pull/31 specified keyword args incorrectly.

```
Traceback (most recent call last):
  File "$PATH/opsreview/pull_alerts.py", line 233, in <module>
    print_all_incidents(
  File "$PATH/opsreview/pull_alerts.py", line 84, in print_all_incidents
    recent_incidents = recent_incidents_for_services(services, timedelta(days=time_window_days))
TypeError: recent_incidents_for_services() missing 1 required positional argument: 'service_ids'
```